# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:
    desc: run fitgpt demo
    cmds:
    - python takethree/main.py
